/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.math.BigInteger;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hemerson Mendes
 */
public class Form_Livro extends javax.swing.JPanel {

    /**
     * Creates new form Form_Editora
     *
     */
    public Form_Livro() {
        initComponents();

        try {
            Constantes.getMet().makeJCBGenero(jcbGenero, false);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Livro.class.getName()).log(Level.SEVERE, null, ex);
        }
        enfeite.setVisible(false);
    }
    private String text;
    private long resultado;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jftISBN = new javax.swing.JFormattedTextField();
        jPanel9 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        jcTitulo = new javax.swing.JLabel();
        jcbTitulo = new javax.swing.JComboBox<>();
        jlTitulo = new javax.swing.JLabel();
        jtTitulo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtEditora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtAutor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcbGenero = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jfData = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        cbAtivo = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        enfeite = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 5, 20));

        jLabel5.setText("ISBN:");
        jPanel1.add(jLabel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jftISBN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###############"))));
        jftISBN.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jftISBNFocusLost(evt);
            }
        });
        jPanel7.add(jftISBN);

        jPanel6.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        btnSearch.setText("+");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel9.add(btnSearch);

        jPanel6.add(jPanel9, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel6);

        jcTitulo.setText("Titulo:");
        jPanel1.add(jcTitulo);

        jcbTitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbTituloActionPerformed(evt);
            }
        });
        jPanel1.add(jcbTitulo);

        jlTitulo.setText("Titulo:");
        jPanel1.add(jlTitulo);

        jtTitulo.setEditable(false);
        jPanel1.add(jtTitulo);

        jLabel7.setText("Editora:");
        jPanel1.add(jLabel7);

        jtEditora.setEditable(false);
        jPanel1.add(jtEditora);

        jLabel8.setText("Autor:");
        jPanel1.add(jLabel8);

        jtAutor.setEditable(false);
        jPanel1.add(jtAutor);

        jLabel9.setText("Genero:");
        jPanel1.add(jLabel9);

        jcbGenero.setEnabled(false);
        jcbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbGeneroActionPerformed(evt);
            }
        });
        jPanel1.add(jcbGenero);

        jLabel10.setText("Publicado:");
        jPanel1.add(jLabel10);

        jfData.setEditable(false);
        jfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        jPanel1.add(jfData);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("L I V R O");
        jPanel2.add(jLabel1);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0));
        jPanel3.add(jLabel2);

        btnSalvar.setText("SALVAR");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel3.add(btnSalvar);
        jPanel3.add(jLabel3);

        jButton2.setText("FECHAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jPanel3.add(jLabel4);

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        cbAtivo.setText("Ativo");
        cbAtivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cbAtivo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel4.add(cbAtivo);

        add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        enfeite.setText("Enf.");
        jPanel5.add(enfeite);

        add(jPanel5, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Constantes.getMain().getJtpMain().remove(Constantes.getMain().getJtpMain().getSelectedComponent());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        text = "";
        if (jcbGenero.getSelectedIndex() == 0 && "EDITAR".equals(btnSalvar.getText())) {
            text = text + "- Por favor escolher um genero!\n";
        }
        if (jftISBN.getText().length() != 13) {
            text = text + "- DDigite um ISBN de exatos 13 digitos!\n";
        }
        if ("".equals(text)) {
            try {
                if ("EDITAR".equals(btnSalvar.getText())) {
                    Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).setAtivo(cbAtivo.isSelected());
                    resultado = Constantes.getMl().doLivro(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1), Constantes.getLgenero().get(jcbGenero.getSelectedIndex() - 1).getGeneroId().toString(), false);
                } else {
                    Constantes.setVwlivro(new VwLivro());
                    Constantes.getVwlivro().setLivroId(BigInteger.valueOf(0));
                    Constantes.getVwlivro().setIsbn(BigInteger.valueOf(Long.valueOf(jftISBN.getText())));
                    Constantes.getVwlivro().setLivro(jtTitulo.getText());
                    Constantes.getVwlivro().setEditora(jtEditora.getText());
                    Constantes.getVwlivro().setAutor(jtAutor.getText());
                    Constantes.getVwlivro().setAtivo(cbAtivo.isSelected());
                    String aux[] = jfData.getText().split("-");
                    Constantes.getVwlivro().setPublicado(java.sql.Date.valueOf(aux[2] + "-" + aux[1] + "-" + aux[0]));

                    resultado = Constantes.getMl().doLivro(Constantes.getVwlivro(), Constantes.getLgenero().get(jcbGenero.getSelectedIndex() - 1).getGeneroId().toString(), false);
                }
                if (btnSalvar.getText().equals("EDITAR")) {
                    if (resultado == 0) {
                        text = "Problema ao realizar a edição de " + Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getLivro().toUpperCase();
                    } else {
                        text = Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getLivro().toUpperCase() + " editado com sucesso!";
                        Limpa();
                    }
                } else {
                    if (resultado == 0) {
                        text = "Problema ao realizar o cadastro de " + Constantes.getVwlivro().getLivro().toUpperCase();
                    } else {
                        text = Constantes.getVwlivro().getLivro().toUpperCase() + " Cadastrado com sucesso!";
                        Limpa();
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(Form_Livro.class.getName()).log(Level.SEVERE, null, ex);
                text = "Erro ao " + btnSalvar.getText().toLowerCase() + "!";
            }
        } else {
            text = "Por favor se atentar ao seguinte: \n\n" + text;
        }
        JOptionPane.showMessageDialog(this, text);
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if ("".equals(jftISBN.getText()) || (jftISBN.getText().length() != 13)) {
            JOptionPane.showMessageDialog(Constantes.getMain(), "Preencha o campo ISBN corretamente (Tam. 13)");
        } else {
            if (Constantes.getMet().CallApi(jftISBN.getText())) {
                jtAutor.setText(Constantes.getVwlivro().getAutor());
                jtEditora.setText(Constantes.getVwlivro().getEditora());
                jtTitulo.setText(Constantes.getVwlivro().getLivro());
                jfData.setText(new SimpleDateFormat("dd-MM-yyyy").format(Constantes.getVwlivro().getPublicado()));
                jcbGenero.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    public JComboBox<String> getJcbGenero() {
        return jcbGenero;
    }

    private void jcbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbGeneroActionPerformed
        btnSalvar.setEnabled(jcbGenero.getSelectedIndex() != 0);
    }//GEN-LAST:event_jcbGeneroActionPerformed

    private void jcbTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbTituloActionPerformed
        Limpa();
        btnSalvar.setEnabled(jcbTitulo.getSelectedIndex() != 0);
        jcbGenero.setEnabled(jcbTitulo.getSelectedIndex() != 0);
        if (jcbTitulo.getSelectedIndex() != 0) {
            cbAtivo.setSelected(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getAtivo());
            jftISBN.setText(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getIsbn().toString());
            jtAutor.setText(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getAutor());
            jtEditora.setText(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getEditora());
            jtTitulo.setText(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getLivro());
            jfData.setText(new SimpleDateFormat("dd-MM-yyyy").format(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getPublicado()));
            jcbGenero.setSelectedIndex(Constantes.getMet().checkGenero(Constantes.getLlivro().get(jcbTitulo.getSelectedIndex() - 1).getGenero()));
        }
    }//GEN-LAST:event_jcbTituloActionPerformed

    private void jftISBNFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jftISBNFocusLost
        if ("".equals(jftISBN.getText())) {
            jftISBN.setValue(null);
        } else {
        }
    }//GEN-LAST:event_jftISBNFocusLost

    public JLabel getJcTitulo() {
        return jcTitulo;
    }

    public JComboBox<String> getJcbTitulo() {
        return jcbTitulo;
    }

    public JLabel getJlTitulo() {
        return jlTitulo;
    }

    public JTextField getJtTitulo() {
        return jtTitulo;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox cbAtivo;
    private javax.swing.JLabel enfeite;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jcTitulo;
    private javax.swing.JComboBox<String> jcbGenero;
    private javax.swing.JComboBox<String> jcbTitulo;
    private javax.swing.JFormattedTextField jfData;
    private javax.swing.JFormattedTextField jftISBN;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtAutor;
    private javax.swing.JTextField jtEditora;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables

    private void Limpa() {
        try {
            Constantes.getMet().makeJCBGenero(jcbGenero, "EDITAR".equals(btnSalvar.getText()));
            jtAutor.setText("");
            jtEditora.setText("");
            jtTitulo.setText("");
            jfData.setText("");
            btnSalvar.setEnabled(false);
            jcbGenero.setEnabled(false);
        } catch (SQLException ex) {
            Logger.getLogger(Form_Livro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public javax.swing.JButton getBtnSearch() {
        return btnSearch;
    }

    public javax.swing.JFormattedTextField getJftISBN() {
        return jftISBN;
    }
}
