/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biblioteca;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Hemerson Mendes
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setIconImage(new ImageIcon(System.getProperty("user.dir") + "\\imagens\\system_icon.png").getImage());
        Constantes.setJson(new Json());
        Constantes.setVwusuario(new VwUsuario());
        Constantes.setVwlivro(new VwLivro());
        Constantes.setMbd(new Metodos_Banco_Post());
        Constantes.setMet(new Metodos_Comum());
        Constantes.setCa(new CallAPI());
        Constantes.setMg(new Metodos_Genero());
        Constantes.setMu(new Metodos_Usuario());
        Constantes.setMl(new Metodos_Livro());
        Constantes.setMi(new Metodos_Importacao());
        Constantes.setLgenero(new ArrayList<>());
        Constantes.setLusuario(new ArrayList<>());
        Constantes.setLlivro(new ArrayList<>());
        cdb = new Conexao_DB(this, true);
        Constantes.getMet().Config(cdb);
        Constantes.getMet().doLogin(cdb, this);
        lNome.setText(Constantes.getVwusuarioLogado().getNome());
        lLogin.setText(Constantes.getVwusuarioLogado().getLogin());

        Constantes.setMain(this);
    }

    // <editor-fold defaultstate="collapsed" desc="Declarações">        
    private final Conexao_DB cdb;
    private Form_Genero fg;
    private Form_Usuario fu;
    private Form_Livro fl;

    // </editor-fold> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuTrocarUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        menuAdm = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuUsuarioc = new javax.swing.JMenuItem();
        menuGeneroc = new javax.swing.JMenuItem();
        menuLivroc = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuUsuarioe = new javax.swing.JMenuItem();
        menuGeneroe = new javax.swing.JMenuItem();
        menuLivroe = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuImportar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(Constantes.getVersion());
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jtpMain.setMinimumSize(new java.awt.Dimension(400, 300));
        jtpMain.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(jtpMain, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        lNome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lNome.setText("TEXTO");
        jPanel5.add(lNome);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        lLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLogin.setText("TEXTO");
        jPanel6.add(lLogin);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);
        getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_END);
        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_START);

        jMenu1.setText("Menu");

        menuTrocarUsuario.setText("Trocar Usuario");
        menuTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuTrocarUsuario);
        jMenu1.add(jSeparator1);

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        menuAdm.setText("Adm");

        jMenu3.setText("Cadastro");

        menuUsuarioc.setText("Usuário");
        menuUsuarioc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariocActionPerformed(evt);
            }
        });
        jMenu3.add(menuUsuarioc);

        menuGeneroc.setText("Genero");
        menuGeneroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGenerocActionPerformed(evt);
            }
        });
        jMenu3.add(menuGeneroc);

        menuLivroc.setText("Livro");
        menuLivroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivrocActionPerformed(evt);
            }
        });
        jMenu3.add(menuLivroc);

        menuAdm.add(jMenu3);

        jMenu2.setText("Edição");

        menuUsuarioe.setText("Usuário");
        menuUsuarioe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuarioeActionPerformed(evt);
            }
        });
        jMenu2.add(menuUsuarioe);

        menuGeneroe.setText("Genero");
        menuGeneroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGeneroeActionPerformed(evt);
            }
        });
        jMenu2.add(menuGeneroe);

        menuLivroe.setText("Livro");
        menuLivroe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLivroeActionPerformed(evt);
            }
        });
        jMenu2.add(menuLivroe);

        menuAdm.add(jMenu2);

        jMenuBar1.add(menuAdm);

        jMenu4.setText("Arquivo");

        menuImportar.setText("Importar");
        menuImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuImportarActionPerformed(evt);
            }
        });
        jMenu4.add(menuImportar);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(1);
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrocarUsuarioActionPerformed
        cdb.setVisible(true);
        lNome.setText(Constantes.getVwusuarioLogado().getNome());
        lLogin.setText(Constantes.getVwusuarioLogado().getLogin());
    }//GEN-LAST:event_menuTrocarUsuarioActionPerformed

    private void menuUsuariocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariocActionPerformed
        fu = new Form_Usuario();
        fu.getJcbUsuario().setVisible(false);
        fu.getLcUsuario().setVisible(false);
        fu.getBtnSalvar().setEnabled(true);
        fu.getCbAtivo().setEnabled(true);
        fu.getCbSenha().setVisible(false);
        fu.getCbSenha().setSelected(true);
        jtpMain.add(fu);
        jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Cad. Usu.");
        jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
    }//GEN-LAST:event_menuUsuariocActionPerformed

    private void menuLivrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivrocActionPerformed
        fl = new Form_Livro();
        fl.getJcTitulo().setVisible(false);
        fl.getJcbTitulo().setVisible(false);
        jtpMain.add(fl);
        jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Cad. Liv.");
        jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
    }//GEN-LAST:event_menuLivrocActionPerformed

    private void menuGenerocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGenerocActionPerformed
        fg = new Form_Genero();
        fg.getJcbGenero().setVisible(false);
        fg.getLcTitulo().setVisible(false);
        fg.getBtnDeletar().setVisible(false);
        fg.getBtnSalvar().setEnabled(true);
        fg.getCbAtivo().setEnabled(true);
        jtpMain.add(fg);
        jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Cad. Gen.");
        jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
    }//GEN-LAST:event_menuGenerocActionPerformed

    private void menuUsuarioeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuarioeActionPerformed
        fu = new Form_Usuario();
        try {
            Constantes.getMu().makeJCBusuario(fu.getJcbUsuario(), true);
            fu.getLtUsuario().setVisible(false);
            fu.getJtUsuario().setVisible(false);
            fu.getJpConfSenha().setEnabled(false);
            fu.getJpSenha().setEnabled(false);
            fu.getBtnSalvar().setText("EDITAR");
            jtpMain.add(fu);
            jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Edi. Usu.");
            jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuUsuarioeActionPerformed

    private void menuGeneroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGeneroeActionPerformed
        fg = new Form_Genero();
        try {
            Constantes.getMet().makeJCBGenero(fg.getJcbGenero(), true);
            fg.getJtGenero().setVisible(false);
            fg.getLtTitulo().setVisible(false);
            fg.getBtnSalvar().setText("EDITAR");
            jtpMain.add(fg);
            jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Edi. Gen.");
            jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuGeneroeActionPerformed

    private void menuLivroeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLivroeActionPerformed
        fl = new Form_Livro();
        try {
            Constantes.getMl().makeJCBLivro(fl.getJcbTitulo(), true);
            fl.getJlTitulo().setVisible(false);
            fl.getJtTitulo().setVisible(false);
            fl.getJftISBN().setEditable(false);
            fl.getBtnSearch().setEnabled(false);
            jtpMain.add(fl);
            jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Cad. Liv.");
            jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuLivroeActionPerformed

    private void menuImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuImportarActionPerformed
        jtpMain.add(new Importacao());
        jtpMain.setTitleAt((jtpMain.getTabCount() - 1), "Importação");
        jtpMain.setSelectedIndex((jtpMain.getTabCount() - 1));
    }//GEN-LAST:event_menuImportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTabbedPane jtpMain;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lNome;
    private javax.swing.JMenu menuAdm;
    private javax.swing.JMenuItem menuGeneroc;
    private javax.swing.JMenuItem menuGeneroe;
    private javax.swing.JMenuItem menuImportar;
    private javax.swing.JMenuItem menuLivroc;
    private javax.swing.JMenuItem menuLivroe;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuTrocarUsuario;
    private javax.swing.JMenuItem menuUsuarioc;
    private javax.swing.JMenuItem menuUsuarioe;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTabbedPane getJtpMain() {
        return jtpMain;
    }
}
